{% set name = "FiPy" %}
{% set version = "3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usnistgov/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 702f1dffc5799e47d879383bbf66bf4f1baa92e40e6241dc9e59845b6ff4df2c

build:
  number: 2
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - future
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - future
    - mpich       # [unix]
    - mpi4py      # [unix]
    - pysparse    # [py2k]
    - petsc4py    # [unix]
    - pytrilinos  # [unix and py2k]
    - mayavi      # [not (win and py2k)]
  # fipy still doesn't support gmsh 4.0, an optional package
  # But gmsh 3 hasn't been built in a long time.
  # So we leave it as an optional dependency should the users want
  # to isntall it.
  # As it is old, it might have some strange pinnings.
  run_constrained:
    - gmsh <4.0   # [not (win and py2k)]

test:
  requires:
    - gmsh        # [not (win and py2k)]
  imports:
    - fipy

about:
  home: http://www.ctcms.nist.gov/fipy
  license: NIST public domain
  license_file: LICENSE.rst
  summary: A finite volume partial differential equation solver using Python
  description: |
    FiPy is an object oriented, partial differential equation (PDE) solver,
    written in Python, based on a standard finite volume (FV) approach. The
    framework has been developed in the Materials Science and Engineering
    Division (MSED) and Center for Theoretical and Computational Materials
    Science (CTCMS), in the Material Measurement Laboratory (MML) at the
    National Institute of Standards and Technology (NIST). The solution of
    coupled sets of PDEs is ubiquitous to the numerical simulation of
    science problems. 
    |
    Numerous PDE solvers exist, using a variety of languages and numerical
    approaches. Many are proprietary, expensive and difficult to customize.
    As a result, scientists spend considerable resources repeatedly
    developing limited tools for specific problems. Our approach, combining
    the FV method and Python, provides a tool that is extensible, powerful
    and freely available. A significant advantage to Python is the existing
    suite of tools for array calculations, sparse matrices and data
    rendering.
    |
    The FiPy framework includes terms for transient diffusion, convection
    and standard sources, enabling the solution of arbitrary combinations
    of coupled elliptic, hyperbolic and parabolic PDEs. Currently
    implemented models include phase field treatments of polycrystalline,
    dendritic, and electrochemical phase transformations as well as a level
    set treatment of the electrodeposition process.
  doc_url: http://www.ctcms.nist.gov/fipy
  dev_url: https://github.com/usnistgov/fipy

extra:
  recipe-maintainers:
    - guyer
